import {cfg,CLOUD} from "./firebase-config.js";import {demoDocs} from "./demo.js";
const $=i=>document.getElementById(i),V="https://www.gstatic.com/firebasejs/10.12.2/",esc=s=>String(s??"").replace(/[&<>"']/g,c=>"&#"+c.charCodeAt(0)+";");
if(cfg.apiKey.startsWith("ضع")){$("lge").textContent="أكمل إعدادات Firebase في firebase-config.js أولًا";throw 0}
const[{initializeApp},A,F]=await Promise.all([import(V+"firebase-app.js"),import(V+"firebase-auth.js"),import(V+"firebase-firestore.js")]);
const app=initializeApp(cfg),au=A.getAuth(app),db=F.getFirestore(app),col=n=>F.collection(db,n),ACI={"ساعات ذكية":"⌚","سماعات رأس":"🎧","سماعات لاسلكية":"🎵","سماعات سلكية":"🎶","شواحن الجوالات":"🔌","كفرات الجوالات":"🛡️"};
let P=[],O=[],RR=[],VS={},BS=[],BNR=null,SVA=[],tab="h",cur=null,img="";
A.onAuthStateChanged(au,u=>{$("lg").style.display=u?"none":"grid";$("ap").style.display=u?"block":"none";if(u)load()});
$("lgb").onclick=async()=>{try{await A.signInWithEmailAndPassword(au,$("em").value.trim(),$("pw").value)}catch(e){$("lge").textContent="بيانات الدخول غير صحيحة"}};$("out").onclick=()=>A.signOut(au);
async function load(){try{P=(await F.getDocs(col("products"))).docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>(a.order||0)-(b.order||0));O=(await F.getDocs(F.query(col("orders"),F.orderBy("at","desc")))).docs.map(d=>({...d.data(),id:d.id}));try{RR=(await F.getDocs(F.query(col("repairs"),F.orderBy("at","desc")))).docs.map(d=>({...d.data(),id:d.id}));VS={};(await F.getDocs(col("visits"))).docs.forEach(d=>VS[d.id]=d.data().n);const b=await F.getDoc(F.doc(db,"settings","branches"));BS=b.exists()?b.data().list:DEFB;const bn=await F.getDoc(F.doc(db,"settings","banner"));BNR=bn.exists()?bn.data():DEFN;const sv=await F.getDoc(F.doc(db,"settings","services"));SVA=sv.exists()?sv.data().list:DEFS}catch(e){console.warn(e);if(!BS.length)BS=DEFB;if(!BNR)BNR=DEFN;if(!SVA.length)SVA=DEFS}
}catch(e){alert("تعذر تحميل البيانات — تأكد من قواعد Firestore وأن بريدك هو المدير")}draw()}
function draw(){["h","p","o","r","b"].forEach(k=>$(k+"v").style.display=tab==k?"block":"none");document.querySelectorAll(".nb button").forEach(b=>b.className=b.dataset.t==tab?"on":"");const nw=O.filter(o=>o.status=="جديد").length+RR.filter(r=>r.status=="جديد").length;$("oc").textContent=nw||"";if(tab=="h")home();if(tab=="r")reps();if(tab=="b")brs();
if(tab=="p"){const q=$("s").value.toLowerCase(),t=$("ft").value;$("list").innerHTML=P.filter(p=>(t=="all"||p.type==t)&&(p.name||"").toLowerCase().includes(q)).map(p=>`<div class="r" data-id="${p.id}"><span class="th">${p.img?`<img src="${esc(p.img.replace("/upload/","/upload/f_auto,q_auto,w_120/"))}">`:esc(p.emoji||"📱")}</span><div class="in"><b>${esc(p.name)}</b><small>${esc(p.brand||p.cat)} · ${p.type=="new"?"جديد":p.type=="used"?"مستعمل":"إكسسوار"}${p.demo?" · تجريبي":""}</small><br><input class="pr" type="number" value="${+p.price}"></div><button class="sw ${p.stock!==false?"on":""}" title="متوفر"></button><button class="ib e">✏️</button><button class="ib d">🗑️</button></div>`).join("")||"<p style='color:var(--mut)'>لا توجد منتجات — اضغط ＋ إضافة أو حمّل التجريبية</p>";
$("dl").innerHTML=[...new Set(P.map(p=>p.brand||p.cat).filter(Boolean))].map(x=>`<option value="${esc(x)}">`).join("")}
else if(tab=="o")$("ov").innerHTML=O.map(o=>`<div class="o"><div class="h"><b>${esc(o.name)} — ₪${+o.total}</b><select data-id="${o.id}">${["جديد","قيد التجهيز","تم","ملغي"].map(s=>`<option${s==o.status?" selected":""}>${s}</option>`).join("")}</select></div><span>📞 ${esc(o.phone)} · 📍 ${esc(o.branch)} · ${esc(o.method)}${o.addr?" — "+esc(o.addr):""}</span><span>${(o.items||[]).map(i=>esc(i.name)+" ×"+(+i.qty)).join("، ")}</span>${o.note?`<span>📝 ${esc(o.note)}</span>`:""}<a target="_blank" href="https://wa.me/${waN(o.phone)}">💬 تواصل مع الزبون</a></div>`).join("")||"<p style='color:var(--mut)'>لا توجد طلبات بعد</p>"}
document.querySelector(".nb").onclick=e=>{const b=e.target.closest("button");if(b){tab=b.dataset.t;draw();scrollTo(0,0)}};$("s").oninput=draw;$("ft").onchange=draw;
$("list").onclick=async e=>{const r=e.target.closest(".r");if(!r)return;const p=P.find(x=>x.id==r.dataset.id);
if(e.target.classList.contains("sw")){p.stock=p.stock===false;await F.updateDoc(F.doc(db,"products",p.id),{stock:p.stock});draw()}
else if(e.target.classList.contains("d")){if(confirm("حذف "+p.name+"؟")){await F.deleteDoc(F.doc(db,"products",p.id));load()}}
else if(e.target.classList.contains("e"))openF(p)};
$("list").onchange=async e=>{if(e.target.classList.contains("pr")){const p=P.find(x=>x.id==e.target.closest(".r").dataset.id);p.price=+e.target.value;await F.updateDoc(F.doc(db,"products",p.id),{price:p.price})}};
$("ov").onchange=async e=>{if(e.target.dataset.id)await F.updateDoc(F.doc(db,"orders",e.target.dataset.id),{status:e.target.value});load()};
const sh=()=>{const t=$("ty").value;$("bl").textContent=t=="acc"?"الفئة":"الماركة";$("gt").style.display=t=="acc"?"grid":"none";$("gb").style.display=t=="acc"?"none":"grid";$("gc").style.display=t=="used"?"grid":"none"};$("ty").onchange=sh;
function openF(p){cur=p;img=p?.img||"";$("mt").textContent=p?"تعديل منتج":"منتج جديد";$("ty").value=p?.type||"new";$("br").value=p?.brand||p?.cat||"";$("nm").value=p?.name||"";$("pc").value=p?.price||"";$("od").value=p?.old||"";$("bd").value=p?.badge||"";$("cd").value=p?.cond||"";$("tm").value=p?.time||"";$("sp").value=p?.specs||"";$("msg").textContent="";prev();sh();$("md").className="md on"}
const prev=()=>{$("upb").innerHTML=(img?`<img src="${esc(img)}">`:"📷 اضغط لاختيار صورة")+'<input id="fi" type="file" accept="image/*" hidden>'};
$("add").onclick=()=>openF(null);$("cx").onclick=()=>$("md").className="md";$("md").onclick=e=>{if(e.target.id=="md")$("md").className="md"};
$("upb").onclick=e=>{if(e.target.id!="fi")$("fi").click()};
$("upb").onchange=async e=>{const f=e.target.files[0];if(!f)return;$("msg").textContent="جاري ضغط الصورة ورفعها…";try{const b=await createImageBitmap(f,{imageOrientation:"from-image"}),s=Math.min(1,1000/Math.max(b.width,b.height)),c=document.createElement("canvas");c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);c.getContext("2d").drawImage(b,0,0,c.width,c.height);
const bl=await new Promise(r=>c.toBlob(r,"image/jpeg",.82)),fd=new FormData();fd.append("file",bl);fd.append("upload_preset",CLOUD.preset);fd.append("folder","albasha");
const j=await(await fetch(`https://api.cloudinary.com/v1_1/${CLOUD.name}/image/upload`,{method:"POST",body:fd})).json();if(!j.secure_url)throw new Error(j.error?.message||"فشل الرفع");img=j.secure_url;prev();$("msg").textContent="✓ تم رفع الصورة ("+Math.round(bl.size/1024)+" KB)"}catch(x){$("msg").textContent="خطأ: "+x.message}};
$("sv").onclick=async()=>{const t=$("ty").value,n=$("nm").value.trim(),pr=+$("pc").value,b=$("br").value.trim();if(!n||!pr||!b){$("msg").textContent="عبّي الاسم والسعر و"+(t=="acc"?"الفئة":"الماركة");return}
const d={type:t,name:n,price:pr,old:+$("od").value||0,specs:$("sp").value.trim(),img,stock:cur?cur.stock!==false:true,order:cur?.order??-Math.floor(Date.now()/1e3)};
if(t=="acc"){d.cat=b;d.emoji=ACI[b]||"🎧";d.time=$("tm").value.trim()}else{d.brand=b;d.badge=$("bd").value.trim();if(t=="used")d.cond=$("cd").value.trim()}
try{cur?await F.setDoc(F.doc(db,"products",cur.id),d,{merge:true}):await F.addDoc(col("products"),d);$("md").className="md";load()}catch(e){$("msg").textContent="تعذر الحفظ: "+e.message}};
$("seed").onclick=async()=>{if(!confirm("تحميل المنتجات التجريبية؟"))return;const b=F.writeBatch(db);demoDocs().forEach(d=>b.set(F.doc(col("products")),{...d,demo:true}));await b.commit();load()};
$("deldemo").onclick=async()=>{const d=P.filter(p=>p.demo);if(!d.length||!confirm("حذف "+d.length+" منتج تجريبي؟"))return;const b=F.writeBatch(db);d.forEach(p=>b.delete(F.doc(db,"products",p.id)));await b.commit();load()};

const DEFB=["خانيونس","النصيرات","المواصي","غزة"].map(n=>({name:n,addr:"",phone:"",hours:"",map:"",active:true}));
const lk=d=>new Date(d.getTime()-d.getTimezoneOffset()*6e4).toISOString().slice(0,10),od=o=>o.at&&o.at.toDate?o.at.toDate():new Date(0);
function home(){const td=lk(new Date()),ts=O.filter(o=>lk(od(o))==td),w=O.filter(o=>Date.now()-od(o)<6048e5&&o.status!="ملغي").reduce((s,o)=>s+(+o.total||0),0),
days=[...Array(7)].map((_,i)=>{const d=new Date(Date.now()-(6-i)*864e5);return[lk(d),["ح","ن","ث","ر","خ","ج","س"][d.getDay()]]}),cn=days.map(x=>O.filter(o=>lk(od(o))==x[0]).length),mx=Math.max(1,...cn);
$("hv").innerHTML=`<h2>نظرة عامة</h2><div class="st"><div class="sc a"><small>طلبات اليوم</small><b>${ts.length}</b></div><div class="sc"><small>منتجات متوفرة</small><b>${P.filter(p=>p.stock!==false).length}</b></div><div class="sc"><small>طلبات صيانة جديدة</small><b>${RR.filter(r=>r.status=="جديد").length}</b></div><div class="sc"><small>قيمة طلبات الأسبوع</small><b>₪${w.toLocaleString()}</b></div><div class="sc"><small>زيارات اليوم</small><b>${VS[td]||0}</b></div></div><div class="cd"><h3>الطلبات آخر 7 أيام</h3><div class="bars">${cn.map((c,i)=>`<span style="height:${Math.max(5,c/mx*100)}%"><u>${c||""}</u><em>${days[i][1]}</em></span>`).join("")}</div></div><div class="cd"><h3>آخر الطلبات</h3>${O.slice(0,5).map(o=>`<div class="od"><span>${esc(o.name)} — ₪${+o.total}<small>${esc(o.branch)}</small></span><span class="pill">${esc(o.status)}</span></div>`).join("")||"<small style='color:var(--mut)'>لا توجد طلبات بعد</small>"}</div>`}
function reps(){$("rv").innerHTML="<h2>طلبات الصيانة</h2>"+(RR.map(r=>`<div class="o"><div class="h"><b>${esc(r.name)} — ${esc(r.device)}</b><select data-rid="${r.id}">${["جديد","قيد الفحص","تم","ملغي"].map(s=>`<option${s==r.status?" selected":""}>${s}</option>`).join("")}</select></div><span>📞 ${esc(r.phone)} · 📍 ${esc(r.branch)}</span>${r.issue?`<span>⚠️ ${esc(r.issue)}</span>`:""}<a target="_blank" href="https://wa.me/${waN(r.phone)}">💬 تواصل مع الزبون</a></div>`).join("")||"<p style='color:var(--mut)'>لا توجد طلبات صيانة بعد</p>")}
$("rv").onchange=async e=>{if(e.target.dataset.rid){await F.updateDoc(F.doc(db,"repairs",e.target.dataset.rid),{status:e.target.value});load()}};
function brs(){$("bv").innerHTML="<h2>الإعدادات</h2>"+bnr()+svc()+"<h2 style='margin-top:18px'>الفروع</h2>"+BS.map((b,i)=>`<div class="cd" data-i="${i}"><div class="br2"><b>فرع ${esc(b.name)}</b><button class="sw ${b.active!==false?"on":""}"></button></div><div class="fm"><label>العنوان<input data-k="addr" value="${esc(b.addr)}"></label><label>رقم الهاتف / واتساب<input data-k="phone" type="tel" value="${esc(b.phone)}"></label><label>ساعات الدوام<input data-k="hours" value="${esc(b.hours)}"></label><label>رابط خرائط Google<input data-k="map" value="${esc(b.map)}"></label></div></div>`).join("")+'<button class="bt" id="bsv" style="width:100%;margin-top:12px">حفظ الفروع</button>'}
$("bv").onclick=async e=>{if(e.target.classList.contains("sw")){e.target.classList.toggle("on");return}if(e.target.id=="sadd"){SVA=colS();SVA.push({icon:"🔧",title:"",desc:"",price:"",active:true});brs();return}
if(e.target.classList.contains("sd")){SVA=colS();SVA.splice(+e.target.closest("[data-s]").dataset.s,1);brs();return}
if(e.target.id=="ssv"){const L=colS().filter(s=>s.title);try{await F.setDoc(F.doc(db,"settings","services"),{list:L});SVA=L;e.target.textContent="✓ تم الحفظ";setTimeout(brs,1200)}catch(x){alert("تعذر الحفظ: "+x.message)}return}
if(e.target.id=="bnsv"){const c=$("bnc"),b={active:c.querySelector(".sw").classList.contains("on")};c.querySelectorAll("[data-b]").forEach(i=>b[i.dataset.b]=i.value.trim());try{await F.setDoc(F.doc(db,"settings","banner"),b);BNR=b;e.target.textContent="✓ تم الحفظ";setTimeout(brs,1200)}catch(x){alert("تعذر الحفظ: "+x.message)}return}if(e.target.id=="bsv"){const L=[...$("bv").querySelectorAll(".cd[data-i]")].map(c=>{const b={...BS[+c.dataset.i]};c.querySelectorAll("input").forEach(i=>b[i.dataset.k]=i.value.trim());b.active=c.querySelector(".sw").classList.contains("on");return b});try{await F.setDoc(F.doc(db,"settings","branches"),{list:L});BS=L;e.target.textContent="✓ تم الحفظ";setTimeout(brs,1200)}catch(x){alert("تعذر الحفظ: "+x.message)}}};

const DEFN={active:true,tag:"الجديد وصل",title:"أحدث الجوالات\nبأفضل الأسعار",text:"جوالات جديدة متوفرة الآن — اطلب عبر واتساب واستلم بسرعة.",btn:"تسوّق الآن ←",msg:""};
function bnr(){const b=BNR||DEFN;return`<div class="cd" id="bnc"><div class="br2"><b>📣 بانر الصفحة الرئيسية</b><button class="sw ${b.active!==false?"on":""}"></button></div><div class="fm"><label>الشارة (مثال: وصلنا حديثًا)<input data-b="tag" value="${esc(b.tag)}"></label><label>العنوان (Enter لسطر جديد)<textarea data-b="title" rows="2">${esc(b.title)}</textarea></label><label>النص<textarea data-b="text" rows="2">${esc(b.text)}</textarea></label><label>نص الزر<input data-b="btn" value="${esc(b.btn)}"></label><label>رسالة واتساب (اختياري)<input data-b="msg" value="${esc(b.msg)}" placeholder="مرحبًا، بدي أستفسر عن iPhone 18 Pro Max"></label></div><button class="bt" id="bnsv" style="width:100%;margin-top:10px">حفظ البانر</button></div>`}

const DEFS=[{icon:"📱",title:"شاشة iPhone 13",desc:"استفسر عن أنواع الشاشات وسعر التركيب",price:"",active:true},{icon:"📱",title:"شاشة Samsung A54",desc:"تأكد من التوفر وتفاصيل الصيانة",price:"",active:true},{icon:"🔋",title:"بطاريات وشحن",desc:"تبديل بطارية ومنفذ شحن",price:"",active:true},{icon:"🛠️",title:"فحص وصيانة عامة",desc:"تشخيص العطل وخيارات الإصلاح",price:"",active:true}];
const colS=()=>[...$("bv").querySelectorAll("#svc .cd[data-s]")].map(c=>{const o={};c.querySelectorAll("[data-v]").forEach(i=>o[i.dataset.v]=i.value.trim());o.active=c.querySelector(".sw").classList.contains("on");return o});
function svc(){return`<h2 style='margin-top:18px'>خدمات الصيانة</h2><div id="svc">${SVA.map((s,i)=>`<div class="cd" data-s="${i}"><div class="br2"><b>خدمة ${i+1}</b><span><button class="sw ${s.active!==false?"on":""}"></button> <button class="ib sd">🗑️</button></span></div><div class="fm"><label>الأيقونة (إيموجي)<input data-v="icon" value="${esc(s.icon)}"></label><label>العنوان<input data-v="title" value="${esc(s.title)}"></label><label>الوصف<input data-v="desc" value="${esc(s.desc)}"></label><label>السعر (اختياري)<input data-v="price" value="${esc(s.price)}" placeholder="يبدأ من ₪150 / حسب الفحص"></label></div></div>`).join("")}<button class="bt g" id="sadd" style="width:100%;margin-top:8px">＋ إضافة خدمة</button><button class="bt" id="ssv" style="width:100%;margin-top:8px">حفظ الخدمات</button></div>`}

const waN=p=>{let d=String(p||"").replace(/\D/g,"").replace(/^00/,"");return /^(970|972)/.test(d)?d:"970"+d.replace(/^0/,"")};
{const b=document.createElement("button");b.className="bt g";b.textContent="⬇️ نسخة احتياطية";$("seed").parentNode.append(b);b.onclick=()=>{const d=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),products:P,branches:BS,banner:BNR,services:SVA},null,1)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(d);a.download="albasha-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5e3)}}
