import {cfg,CLOUD} from "./firebase-config.js";import {demoDocs} from "./demo.js";
const $=i=>document.getElementById(i),V="https://www.gstatic.com/firebasejs/10.12.2/",esc=s=>String(s??"").replace(/[&<>"']/g,c=>"&#"+c.charCodeAt(0)+";");
if(cfg.apiKey.startsWith("ضع")){$("lge").textContent="أكمل إعدادات Firebase في firebase-config.js أولًا";throw 0}
const[{initializeApp},A,F]=await Promise.all([import(V+"firebase-app.js"),import(V+"firebase-auth.js"),import(V+"firebase-firestore.js")]);
const app=initializeApp(cfg),au=A.getAuth(app),db=F.getFirestore(app),col=n=>F.collection(db,n),ACI={"ساعات ذكية":"⌚","سماعات رأس":"🎧","سماعات لاسلكية":"🎵","سماعات سلكية":"🎶","شواحن الجوالات":"🔌","كفرات الجوالات":"🛡️"};
let P=[],O=[],tab="p",cur=null,img="";
A.onAuthStateChanged(au,u=>{$("lg").style.display=u?"none":"grid";$("ap").style.display=u?"block":"none";if(u)load()});
$("lgb").onclick=async()=>{try{await A.signInWithEmailAndPassword(au,$("em").value.trim(),$("pw").value)}catch(e){$("lge").textContent="بيانات الدخول غير صحيحة"}};$("out").onclick=()=>A.signOut(au);
async function load(){try{P=(await F.getDocs(col("products"))).docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>(a.order||0)-(b.order||0));O=(await F.getDocs(F.query(col("orders"),F.orderBy("at","desc")))).docs.map(d=>({...d.data(),id:d.id}))}catch(e){alert("تعذر تحميل البيانات — تأكد من قواعد Firestore وأن بريدك هو المدير")}draw()}
function draw(){$("pv").style.display=tab=="p"?"block":"none";$("ov").style.display=tab=="o"?"block":"none";$("tp").className=tab=="p"?"on":"";$("to").className=tab=="o"?"on":"";const nw=O.filter(o=>o.status=="جديد").length;$("oc").textContent=nw?"("+nw+")":"";
if(tab=="p"){const q=$("s").value.toLowerCase(),t=$("ft").value;$("list").innerHTML=P.filter(p=>(t=="all"||p.type==t)&&(p.name||"").toLowerCase().includes(q)).map(p=>`<div class="r" data-id="${p.id}"><span class="th">${p.img?`<img src="${esc(p.img.replace("/upload/","/upload/f_auto,q_auto,w_120/"))}">`:p.emoji||"📱"}</span><div class="in"><b>${esc(p.name)}</b><small>${esc(p.brand||p.cat)} · ${p.type=="new"?"جديد":p.type=="used"?"مستعمل":"إكسسوار"}${p.demo?" · تجريبي":""}</small><br><input class="pr" type="number" value="${+p.price}"></div><button class="sw ${p.stock!==false?"on":""}" title="متوفر"></button><button class="ib e">✏️</button><button class="ib d">🗑️</button></div>`).join("")||"<p style='color:var(--mut)'>لا توجد منتجات — اضغط ＋ إضافة أو حمّل التجريبية</p>";
$("dl").innerHTML=[...new Set(P.map(p=>p.brand||p.cat).filter(Boolean))].map(x=>`<option value="${esc(x)}">`).join("")}
else $("ov").innerHTML=O.map(o=>`<div class="o"><div class="h"><b>${esc(o.name)} — ₪${+o.total}</b><select data-id="${o.id}">${["جديد","قيد التجهيز","تم","ملغي"].map(s=>`<option${s==o.status?" selected":""}>${s}</option>`).join("")}</select></div><span>📞 ${esc(o.phone)} · 📍 ${esc(o.branch)} · ${esc(o.method)}${o.addr?" — "+esc(o.addr):""}</span><span>${(o.items||[]).map(i=>esc(i.name)+" ×"+(+i.qty)).join("، ")}</span>${o.note?`<span>📝 ${esc(o.note)}</span>`:""}<a target="_blank" href="https://wa.me/970${String(o.phone).replace(/\D/g,"").replace(/^0/,"")}">💬 تواصل مع الزبون</a></div>`).join("")||"<p style='color:var(--mut)'>لا توجد طلبات بعد</p>"}
$("tp").onclick=()=>{tab="p";draw()};$("to").onclick=()=>{tab="o";draw()};$("s").oninput=draw;$("ft").onchange=draw;
$("list").onclick=async e=>{const r=e.target.closest(".r");if(!r)return;const p=P.find(x=>x.id==r.dataset.id);
if(e.target.classList.contains("sw")){p.stock=p.stock===false;await F.updateDoc(F.doc(db,"products",p.id),{stock:p.stock});draw()}
else if(e.target.classList.contains("d")){if(confirm("حذف "+p.name+"؟")){await F.deleteDoc(F.doc(db,"products",p.id));load()}}
else if(e.target.classList.contains("e"))openF(p)};
$("list").onchange=async e=>{if(e.target.classList.contains("pr")){const p=P.find(x=>x.id==e.target.closest(".r").dataset.id);p.price=+e.target.value;await F.updateDoc(F.doc(db,"products",p.id),{price:p.price})}};
$("ov").onchange=async e=>{if(e.target.dataset.id)await F.updateDoc(F.doc(db,"orders",e.target.dataset.id),{status:e.target.value});load()};
const sh=()=>{const t=$("ty").value;$("bl").textContent=t=="acc"?"الفئة":"الماركة";$("gt").style.display=t=="acc"?"grid":"none";$("gb").style.display=t=="acc"?"none":"grid";$("gc").style.display=t=="used"?"grid":"none"};$("ty").onchange=sh;
function openF(p){cur=p;img=p?.img||"";$("mt").textContent=p?"تعديل منتج":"منتج جديد";$("ty").value=p?.type||"new";$("br").value=p?.brand||p?.cat||"";$("nm").value=p?.name||"";$("pc").value=p?.price||"";$("od").value=p?.old||"";$("bd").value=p?.badge||"";$("cd").value=p?.cond||"";$("tm").value=p?.time||"";$("sp").value=p?.specs||"";$("msg").textContent="";prev();sh();$("md").className="md on"}
const prev=()=>{$("upb").innerHTML=(img?`<img src="${esc(img)}">`:"📷 اضغط لاختيار صورة")+'<input id="fi" type="file" accept="image/*" hidden>'};
$("add").onclick=()=>openF(null);$("cx").onclick=()=>$("md").className="md";$("md").onclick=e=>{if(e.target.id=="md")$("md").className="md"};
$("upb").onclick=e=>{if(e.target.id!="fi")$("fi").click()};
$("upb").onchange=async e=>{const f=e.target.files[0];if(!f)return;$("msg").textContent="جاري ضغط الصورة ورفعها…";try{const b=await createImageBitmap(f,{imageOrientation:"from-image"}),s=Math.min(1,1000/Math.max(b.width,b.height)),c=document.createElement("canvas");c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);c.getContext("2d").drawImage(b,0,0,c.width,c.height);
const bl=await new Promise(r=>c.toBlob(r,"image/jpeg",.82)),fd=new FormData();fd.append("file",bl);fd.append("upload_preset",CLOUD.preset);fd.append("folder","albasha");
const j=await(await fetch(`https://api.cloudinary.com/v1_1/${CLOUD.name}/image/upload`,{method:"POST",body:fd})).json();if(!j.secure_url)throw new Error(j.error?.message||"فشل الرفع");img=j.secure_url;prev();$("msg").textContent="✓ تم رفع الصورة ("+Math.round(bl.size/1024)+" KB)"}catch(x){$("msg").textContent="خطأ: "+x.message}};
$("sv").onclick=async()=>{const t=$("ty").value,n=$("nm").value.trim(),pr=+$("pc").value,b=$("br").value.trim();if(!n||!pr||!b){$("msg").textContent="عبّي الاسم والسعر و"+(t=="acc"?"الفئة":"الماركة");return}
const d={type:t,name:n,price:pr,old:+$("od").value||0,specs:$("sp").value.trim(),img,stock:cur?cur.stock!==false:true,order:cur?.order??-Math.floor(Date.now()/1e3)};
if(t=="acc"){d.cat=b;d.emoji=ACI[b]||"🎧";d.time=$("tm").value.trim()}else{d.brand=b;d.badge=$("bd").value.trim();if(t=="used")d.cond=$("cd").value.trim()}
try{cur?await F.setDoc(F.doc(db,"products",cur.id),d,{merge:true}):await F.addDoc(col("products"),d);$("md").className="md";load()}catch(e){$("msg").textContent="تعذر الحفظ: "+e.message}};
$("seed").onclick=async()=>{if(!confirm("تحميل المنتجات التجريبية؟"))return;const b=F.writeBatch(db);demoDocs().forEach(d=>b.set(F.doc(col("products")),{...d,demo:true}));await b.commit();load()};
$("deldemo").onclick=async()=>{const d=P.filter(p=>p.demo);if(!d.length||!confirm("حذف "+d.length+" منتج تجريبي؟"))return;const b=F.writeBatch(db);d.forEach(p=>b.delete(F.doc(db,"products",p.id)));await b.commit();load()};
