import {cfg,BR} from "./firebase-config.js";
import {demoDocs} from "./demo.js";
const $=i=>document.getElementById(i),V="https://www.gstatic.com/firebasejs/10.12.2/",ON=cfg.apiKey&&!cfg.apiKey.startsWith("ضع");
const ACI={"ساعات ذكية":"⌚","سماعات رأس":"🎧","سماعات لاسلكية":"🎵","سماعات سلكية":"🎶","شواحن الجوالات":"🔌","كفرات الجوالات":"🛡️"};
let P=[],cart={},q="",X={},LD=ON,SCREENS=[];
const cl=(u,w)=>u.includes("/upload/")?u.replace("/upload/","/upload/f_auto,q_auto,w_"+w+"/"):u,g=id=>P.find(p=>p.id==id);
const fx=async()=>{const[a,f]=await Promise.all([import(V+"firebase-app.js"),import(V+"firebase-firestore.js")]);return{f,db:f.getFirestore(a.initializeApp(cfg))}};
const money=n=>"₪"+(+n).toLocaleString();
function vis(p){if(p.img)return`<img loading="lazy" decoding="async" onload="this.classList.add('ok')" onerror="this.classList.add('ok')" src="${E(cl(p.img,300))}" alt="${E(p.name)}">`;if(p.type=="acc")return`<span class="ic">${p.emoji||"🎧"}</span>`;const c=(p.colors||"#2b4bd0,#050b22").split(",");return`<div class="p" style="background:linear-gradient(160deg,${c[0]},${c[1]})"></div>`}
function card(p,i){const d=p.old?Math.round((1-p.price/p.old)*100):0,a=p.type=="acc";return`<div class="pd rv${a?" ac":""}" style="--d:${Math.min(i||0,5)*.06}s"><div class="pi${p.img?" im":""}">${a?"":`<span class="bg">${E(p.badge)}</span>`}${d>0?`<span class="ds">-${d}%</span>`:""}${vis(p)}</div><div class="pb">${a?"":`<small>${E(p.brand)}</small>`}<h3>${E(p.name)}</h3>${a?`<span class="tm">⏱ ${E(p.time)}</span><span class="sq">${E(p.specs)}</span>`:`<span class="sp">${p.type=="used"?"مستعمل · "+E(p.cond||"بحالة ممتازة"):"متوفر للاستفسار"}</span>`}<div class="pr"><span><b>${money(p.price)}</b>${p.old?`<s>${money(p.old)}</s>`:""}</span><button onclick="A('${p.id}')" aria-label="أضف ${E(p.name)} للسلة">＋</button></div></div></div>`}
function row(k,title,name,L){if(!L.length)return"";const ex=X[k]&&L.length>6;return`<div class="bb"><div class="bh"><h3>${title}</h3>${L.length>6?`<button data-k="${k}">${ex?"عرض أقل ↑":k[0]=="a"?"عرض الكل ←":"عرض كل جوالات "+name+" ←"}</button>`:""}</div><div class="gr${ex?" ex":""}">${(ex?L:L.slice(0,6)).map(card).join("")}</div></div>`}
function R(){setTimeout(RV,0);setTimeout(()=>{[["new","new"],["used","used"],["acc","acc"]].forEach(([t,id])=>{const e=P.some(p=>p.type==t)||(t=="new"&&!P.length),s=document.getElementById(id),l=document.querySelector('.nv a[href="#'+id+'"]');if(s)s.style.display=e?"":"none";if(l)l.style.display=e?"":"none"});const ok=id=>{const s=document.getElementById(id);return s&&s.style.display!="none"};document.querySelectorAll(".cats a").forEach(c=>{const t=c.getAttribute("href").slice(1);c.style.display=ok(t)?"":"none"});const h3=document.querySelector(".h3"),sd=document.querySelector(".side");if(h3&&sd){const o=ok("acc");h3.style.display=o?"":"none";sd.style.gridTemplateColumns=o?"":"1fr"}},0);const f=p=>((p.name||"")+(p.specs||"")).toLowerCase().includes(q),u=a=>[...new Set(a)];
[["new","gn"],["used","gu"]].forEach(([t,id])=>{$(id).innerHTML=u(P.filter(p=>p.type==t).map(p=>p.brand)).map(b=>row(t+b,b,b,P.filter(p=>p.type==t&&p.brand==b&&f(p)))).join("")||'<p style="color:var(--mut)">'+(LD?"جاري تحميل المنتجات…":"لا توجد منتجات حاليًا")+'</p>'});
$("ga").innerHTML=u(P.filter(p=>p.type=="acc").map(p=>p.cat)).map(c=>row("a"+c,(ACI[c]||"🎧")+" "+c,c,P.filter(p=>p.type=="acc"&&p.cat==c&&f(p)))).join("")}
["gn","gu","ga"].forEach(id=>$(id).onclick=e=>{const k=e.target.getAttribute("data-k");if(k){X[k]=!X[k];R()}});
$("q").oninput=function(){q=this.value.toLowerCase();R()};
function applyCatalog(d){try{if(d.products&&d.products.length){P=d.products.filter(p=>p.stock!==false).sort((x,y)=>(x.order||0)-(y.order||0));try{localStorage.setItem("bp",JSON.stringify(P))}catch(e){}}
if(d.branches&&d.branches.length){BRS=d.branches;try{localStorage.setItem("bb",JSON.stringify(BRS))}catch(e){}RB()}
if(d.banner){BNR=d.banner;try{localStorage.setItem("bn",JSON.stringify(BNR))}catch(e){}RN()}
if(d.services){SVS=d.services;try{localStorage.setItem("sv",JSON.stringify(SVS))}catch(e){}RSV()}
LD=false;R();U()}catch(e){console.warn(e)}}
async function legacy(f,db){const s=await f.getDocs(f.collection(db,"products")),a=s.docs.map(d=>({...d.data(),id:d.id})).filter(p=>p.stock!==false).sort((x,y)=>(x.order||0)-(y.order||0));P=a;try{localStorage.setItem("bp",JSON.stringify(a))}catch(e){}
for(const[k,set]of[["branches",d=>{if(d.list){BRS=d.list;RB()}}],["banner",d=>{BNR=d;RN()}],["services",d=>{if(d.list){SVS=d.list;RSV()}}],["screens",d=>{if(d.list){SCREENS=d.list;RSV()}}]]){try{const x=await f.getDoc(f.doc(db,"settings",k));if(x.exists())set(x.data())}catch(e){}}R();U()}
async function load(){try{P=JSON.parse(localStorage.getItem("bp")||"null")}catch(e){}if(!P||!P.length)P=ON?[]:demoDocs().map((d,i)=>({...d,id:"d"+i}));R();U();if(!ON){LD=false;R();return}
try{const{f,db}=await fx();
try{const ps=await f.getDocs(f.collection(db,"products"));const latest=ps.docs.map(d=>({...d.data(),id:d.id})).filter(p=>p.stock!==false).sort((x,y)=>(x.order||0)-(y.order||0));if(latest.length){P=latest;try{localStorage.setItem("bp",JSON.stringify(P))}catch(e){}R();U()}}catch(e){console.warn("products load",e)}
await new Promise(res=>{let first=true;f.onSnapshot(f.doc(db,"settings","catalog"),async s=>{try{if(s.exists()){const d=s.data()||{};if(Array.isArray(d.products)&&d.products.length)applyCatalog(d);else{try{const ps=await f.getDocs(f.collection(db,"products"));const latest=ps.docs.map(d=>({...d.data(),id:d.id})).filter(p=>p.stock!==false).sort((x,y)=>(x.order||0)-(y.order||0));if(latest.length){P=latest;try{localStorage.setItem("bp",JSON.stringify(P))}catch(e){}R();U()}}catch(e){console.warn("products fallback",e)}applyCatalog({...d,products:P})}}else if(first)await legacy(f,db)}catch(e){console.warn(e)}first=false;res()},e=>{console.warn(e);res()})});
try{if(!sessionStorage.getItem("bv")){sessionStorage.setItem("bv","1");const n=new Date(),d=new Date(n-n.getTimezoneOffset()*6e4).toISOString().slice(0,10),r=f.doc(db,"visits",d);try{await f.updateDoc(r,{n:f.increment(1)})}catch(e){await f.setDoc(r,{n:1})}}}catch(e){}
}catch(e){console.warn(e)}finally{LD=false;R()}}
/* ---- السلة ---- */
try{cart=JSON.parse(localStorage.getItem("bc")||"{}")||{}}catch(e){}
const S=()=>{try{localStorage.setItem("bc",JSON.stringify(cart))}catch(e){}},ids=()=>Object.keys(cart).filter(g),cnt=()=>ids().reduce((s,k)=>s+cart[k],0),tot=()=>ids().reduce((s,k)=>s+cart[k]*g(k).price,0);
const T=t=>{const e=$("ktoast");e.textContent=t;e.className="on";clearTimeout(T.t);T.t=setTimeout(()=>e.className="",1800)};
window.A=id=>{const p=g(id),ct=$("cart");ct.classList.remove("bump");void ct.offsetWidth;ct.classList.add("bump");cart[id]=p.type=="used"?1:(cart[id]||0)+1;S();U();T("تمت الإضافة للسلة ✓")};
window.Qy=(id,d)=>{let v=(cart[id]||0)+d;if(g(id).type=="used"&&v>1)v=1;v<=0?delete cart[id]:cart[id]=v;S();U()};
function U(){$("n").textContent=cnt();if($("bn"))$("bn").textContent=cnt();if($("ksh").className=="on")RC()}
function RC(){const k=ids(),e=!k.length;$("kdone").style.display="none";
$("kit").innerHTML=e?'<div class="ke"><span>🛒</span><b>سلتك فاضية</b><p>أضف جوالات أو إكسسوارات من المتجر</p></div>':k.map(i=>{const p=g(i),c=(p.colors||"#2b4bd0,#050b22");return`<div class="ki"><span class="kt" style="${p.img||p.type=="acc"?"":"background:linear-gradient(160deg,"+c+")"}">${p.img?`<img src="${E(cl(p.img,120))}" alt="">`:p.type=="acc"?p.emoji||"🎧":""}</span><div class="kn2"><b>${E(p.name)}</b><small>${p.type=="used"?"مستعمل · قطعة واحدة":E(p.brand||p.cat)}</small><span>${money(p.price*cart[i])}</span></div><div class="kq"><button onclick="Qy('${i}',1)" aria-label="زيادة الكمية">＋</button><i>${cart[i]}</i><button onclick="Qy('${i}',-1)" aria-label="إنقاص الكمية">−</button></div></div>`}).join("");
$("kform").style.display=e?"none":"block";$("ktot").textContent=money(tot())}
window.K=o=>{$("bsh").className="";$("rsh").className="";$("ksh").className=o?"on":"";$("kov").className=o?"on":"";document.body.style.overflow=o?"hidden":"";if(o)RC()};
window.KE=()=>{if(confirm("تفريغ السلة؟")){cart={};S();U();RC()}};
window.KS=async()=>{const n=$("kname").value.trim(),p=$("kphone").value.replace(/\D/g,""),dl=$("kmeth").value=="توصيل",a=$("kaddr").value.trim(),er=$("kerr"),br=$("kbr").value,nt=$("knote").value.trim();
if(!n)return er.textContent="اكتب اسمك";if(p.length<9)return er.textContent="اكتب رقم جوال صحيح";if(dl&&!a)return er.textContent="اكتب عنوان التوصيل";er.textContent="";
const k=ids(),L=k.map((i,x)=>{const q=g(i);return(x+1)+") "+q.name+(q.type=="used"?" (مستعمل)":"")+" × "+cart[i]+" — "+money(q.price*cart[i])}).join("\n");
const m="🛒 طلب جديد — الباشا فون\n\n👤 الاسم: "+n+"\n📞 الجوال: "+p+"\n📍 الفرع: "+br+"\n🚚 الاستلام: "+$("kmeth").value+(dl?" — "+a:"")+"\n\n"+L+"\n\n💰 الإجمالي: "+money(tot())+(nt?"\n📝 ملاحظات: "+nt:"");
const o={name:n,phone:p,branch:br,method:$("kmeth").value,addr:a,note:nt,total:tot(),items:k.map(i=>({id:i,name:g(i).name,qty:cart[i],price:+g(i).price}))};
window.open("https://wa.me/"+wa(BRS.find(b=>b.name==br)||BRS[0])+"?text="+encodeURIComponent(m),"_blank");
if(ON)try{const{f,db}=await fx();await f.addDoc(f.collection(db,"orders"),{...o,status:"جديد",at:f.serverTimestamp()})}catch(e){}
cart={};S();U();$("kit").innerHTML="";$("kform").style.display="none";$("kdone").style.display="block"};
$("cart").onclick=()=>K(1);
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
const DB=Object.keys(BR).map(n=>({name:n,addr:n=="خانيونس"?"وسط شارع جلال":"",phone:"0592936150",hours:"",map:"",active:true}));
let BRS=DB;try{BRS=JSON.parse(localStorage.getItem("bb"))||DB}catch(e){}
const wa=b=>{let d=String(b.phone||"").replace(/\D/g,"").replace(/^00/,"");if(d.length<9)return"970592936150";return /^(970|972)/.test(d)?d:"970"+d.replace(/^0/,"")};
function RB(){const L=BRS.filter(b=>b.active!==false);$("gb").innerHTML=L.map((b,i)=>`<div class="bx">${i==0?'<span class="m">الفرع الرئيسي</span>':""}<em>📍</em><h3>فرع ${E(b.name)}</h3><p>${E(b.addr)||"للعنوان تواصل معنا عبر واتساب"}${b.hours?"<br>🕒 "+E(b.hours):""}</p><div class="r"><a href="tel:+${wa(b)}">📞 اتصل</a><a href="https://wa.me/${wa(b)}" target="_blank" rel="noopener">💬 واتساب</a>${/^https?:\/\//.test(b.map||"")?`<a class="mp" href="${E(b.map)}" target="_blank" rel="noopener">🗺️ الخريطة</a>`:""}</div></div>`).join("");const o=L.map(b=>`<option>${E(b.name)}</option>`).join("");$("kbr").innerHTML=o;$("rbr").innerHTML=o}
window.RP=o=>{$("ksh").className="";$("rsh").className=o?"on":"";$("kov").className=o?"on":"";document.body.style.overflow=o?"hidden":"";if(o){$("rform").style.display="block";$("rdone").style.display="none"}};
window.RS=async()=>{const n=$("rname").value.trim(),p=$("rphone").value.replace(/\D/g,""),d=$("rdev").value.trim(),i=$("risu").value.trim(),br=$("rbr").value,er=$("rerr");if(!n)return er.textContent="اكتب اسمك";if(p.length<9)return er.textContent="اكتب رقم جوال صحيح";if(!d)return er.textContent="اكتب نوع الجهاز";er.textContent="";
const m="🔧 طلب صيانة — الباشا فون\n\n👤 الاسم: "+n+"\n📞 الجوال: "+p+"\n📍 الفرع: "+br+"\n📱 الجهاز: "+d+(i?"\n⚠️ المشكلة: "+i:"");
window.open("https://wa.me/"+wa(BRS.find(b=>b.name==br)||BRS[0])+"?text="+encodeURIComponent(m),"_blank");
if(ON)try{const{f,db}=await fx();await f.addDoc(f.collection(db,"repairs"),{name:n,phone:p,branch:br,device:d,issue:i,status:"جديد",at:f.serverTimestamp()})}catch(e){}
$("rform").style.display="none";$("rdone").style.display="block"};
const DN={active:true,tag:"الجديد وصل",title:"أحدث الجوالات\nبأفضل الأسعار",text:"جوالات جديدة متوفرة الآن — اطلب عبر واتساب واستلم بسرعة.",btn:"تسوّق الآن ←",msg:""};
let BNR=DN;try{BNR=JSON.parse(localStorage.getItem("bn"))||DN}catch(e){}
const E=s=>String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function RN(){const b=BNR;$("hbn").style.display=b.active===false?"none":"";$("bt").textContent=b.tag||"";$("bh").innerHTML=E(b.title).replace(/\n/g,"<br>");$("bp").textContent=b.text||"";$("bb").textContent=b.btn||"تسوّق الآن ←"}
window.BN=()=>{const L=BRS.filter(b=>b.active!==false);if(L.length==1)return BW(0);$("ksh").className="";$("rsh").className="";$("bsh").className="on";$("kov").className="on";document.body.style.overflow="hidden";$("bl").innerHTML=L.map((b,i)=>`<button class="ks" onclick="BW(${i})">💬 فرع ${E(b.name)}${b.addr?" — "+E(b.addr):""}</button>`).join("")};
window.BW=i=>{const b=BRS.filter(x=>x.active!==false)[i],t=BNR.msg||"مرحبًا الباشا فون 👋\nبدي أستفسر عن: "+String(BNR.title||"").replace(/\n/g," ");window.open("https://wa.me/"+wa(b)+"?text="+encodeURIComponent(t),"_blank");K(0)};
const IO="IntersectionObserver"in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");IO.unobserve(e.target)}}),{threshold:.08,rootMargin:"0px 0px -4% 0px"}):null;
function RV(){document.querySelectorAll(".hb,.cats a,.sh,.rc,.rb,.bx,.tr div,.br div").forEach((e,i)=>{if(!e.classList.contains("rv")){e.classList.add("rv");e.style.setProperty("--d",(i%4)*.07+"s")}});document.querySelectorAll(".rv:not([data-o])").forEach(e=>{e.setAttribute("data-o","1");IO?IO.observe(e):e.classList.add("in")})}
const NA=[...document.querySelectorAll(".nv a")],SEC=NA.map(x=>document.querySelector(x.getAttribute("href"))),ST=new Set();let SO=null;
function SPI(){const H=document.querySelector("header").offsetHeight;document.documentElement.style.scrollPaddingTop=(H+6)+"px";if(SO)SO.disconnect();ST.clear();if(!("IntersectionObserver"in window))return;
SO=new IntersectionObserver(es=>{es.forEach(e=>e.isIntersecting?ST.add(e.target):ST.delete(e.target));let k=-1;SEC.forEach((s,i)=>{if(ST.has(s))k=i});NA.forEach((x,i)=>x.classList.toggle("on",i==k));const L=NA[k];if(!L){SPI.l=null;return}if(L!==SPI.l){SPI.l=L;const c=L.parentNode,r=L.getBoundingClientRect(),q=c.getBoundingClientRect();if(r.left<q.left||r.right>q.right)c.scrollTo({left:c.scrollLeft+(r.left+r.width/2)-(q.left+q.width/2),behavior:"smooth"})}},{rootMargin:"-"+(H+8)+"px 0px -62% 0px"});SEC.forEach(s=>s&&SO.observe(s))}
document.addEventListener("click",e=>{const k=e.target.closest('a[href^="#"]');if(!k||k.getAttribute("href").length<2)return;const t=document.querySelector(k.getAttribute("href"));if(!t)return;e.preventDefault();const go=b=>{const h=document.querySelector("header").offsetHeight,d=t.getBoundingClientRect().top-h-6;if(b=="smooth"||Math.abs(d)>8)scrollTo({top:scrollY+d,behavior:b})};go("smooth");setTimeout(()=>go("instant"),1100);setTimeout(()=>go("instant"),1800)});
let RT;addEventListener("resize",()=>{clearTimeout(RT);RT=setTimeout(SPI,200)});addEventListener("load",SPI);addEventListener("load",()=>{const m=document.querySelector(".mobile-nav");if(!m)return;const links=[...m.querySelectorAll("a")],targets=links.map(a=>document.querySelector(a.getAttribute("href"))).filter(Boolean);const set=k=>links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==k));m.addEventListener("click",e=>{const a=e.target.closest("a");if(a)set(a.getAttribute("href"))});if("IntersectionObserver"in window){const io=new IntersectionObserver(es=>{const hit=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(hit){const a=links.find(x=>x.getAttribute("href")=="#"+hit.target.id);if(a)set(a.getAttribute("href"))}},{rootMargin:"-25% 0px -60% 0px",threshold:[.1,.35,.6]});targets.forEach(t=>io.observe(t))}});
try{if(/[?&]utm_/.test(location.search))history.replaceState(null,"",location.pathname+location.hash)}catch(e){}
const DSV=[{icon:"📱",title:"شاشة iPhone 13",desc:"استفسر عن أنواع الشاشات وسعر التركيب",price:"",active:true},{icon:"📱",title:"شاشة Samsung A54",desc:"تأكد من التوفر وتفاصيل الصيانة",price:"",active:true},{icon:"🔋",title:"بطاريات وشحن",desc:"تبديل بطارية ومنفذ شحن",price:"",active:true},{icon:"🛠️",title:"فحص وصيانة عامة",desc:"تشخيص العطل وخيارات الإصلاح",price:"",active:true}];
let SVS=DSV;try{SVS=JSON.parse(localStorage.getItem("sv"))||DSV;SCREENS=JSON.parse(localStorage.getItem("screens")||"[]")}catch(e){}
function RSV(){const rp=document.querySelector(".rp");if(!rp)return;const screens=SCREENS.filter(s=>s.active!==false&&s.device);const services=SVS.filter(s=>s.active!==false&&s.title);if(!screens.length&&!services.length){rp.style.display="none";return}rp.style.display="";rp.innerHTML=[...screens.map((s,i)=>`<div class="rc screen-card"><em>${s.img?`<img loading="lazy" src="${E(cl(s.img,180))}" alt="${E(s.device)}">`:"▣"}</em><h3>${E(s.device)}</h3><p>${E(s.type||"شاشة متوفرة")}</p>${s.price?`<span style="color:var(--or);font-weight:900;display:block;margin:2px 0 6px">₪${(+s.price).toLocaleString()}</span>`:""}<a href="#" data-screen="${i}">استفسر ↗</a></div>`),...services.map((s,i)=>`<div class="rc"><em>${E(s.icon||"🔧")}</em><h3>${E(s.title)}</h3><p>${E(s.desc)}</p>${s.price?`<span style="color:var(--or);font-weight:900;display:block;margin:2px 0 6px">${E(s.price)}</span>`:""}<a href="#" data-service="${i}">احجز / استفسر ↗</a></div>`)].join("");setTimeout(RV,0)}
document.querySelector(".rp")&&(document.querySelector(".rp").onclick=e=>{const k=e.target.closest("a[data-screen],a[data-service]");if(!k)return;e.preventDefault();let title="";if(k.dataset.screen){const s=SCREENS.filter(x=>x.active!==false&&x.device)[+k.dataset.screen];title=s?s.device+" — "+(s.type||"شاشة"):""}else{const s=SVS.filter(x=>x.active!==false&&x.title)[+k.dataset.service];title=s?s.title:""}RP(1);$("risu").value=title});
